stages:
  - lint
  - tests
  - release

.poetry_install: &poetry_install
  - python -m pip install --user pipx
  - python -m pipx ensurepath
  - source ~/.profile
  - pipx install poetry==1.5.1
  - poetry install --no-interaction --no-root

.install_pydev_for_3_13_only: &install_pydev_for_3_13_only
  - |- 
        if  [[ $(python --version) == 'Python 3.13'* ]]; then
            apt update; 
            apt install -y libopenblas-dev gfortran; 
        fi

lint:
  image: python:$VERSION
  stage: lint
  rules:
    - if: $SHOULD_LINT == "true" && $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $SHOULD_LINT == "true" && $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - *install_pydev_for_3_13_only
    - *poetry_install
    - poetry run black tergite --check
  parallel:
    matrix:
      - VERSION: ['3.9-slim', '3.10-slim', '3.11-slim', '3.12-slim', '3.13-bookworm']

test:
  image: python:$VERSION
  stage: tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - *install_pydev_for_3_13_only
    - *poetry_install
    - poetry run pytest tests/
  parallel:
    matrix:
      - VERSION: ['3.9-slim', '3.10-slim', '3.11-slim', '3.12-slim', '3.13-bookworm']


deploy staging:
  stage: release
  environment: staging
  image: python:3.9-slim
  rules:
    - if: $SHOULD_PUBLISH_TO_STAGING == "true" && $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - *poetry_install
    - poetry config repositories.test-pypi https://test.pypi.org/legacy/
    - poetry config pypi-token.test-pypi $TEST_PYPI_API_TOKEN
    - poetry publish -r test-pypi

deploy production:
  stage: release
  environment: production
  image: python:3.9-slim
  rules:
    - if: $SHOULD_PUBLISH_TO_PROD == "true" && $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - *poetry_install
    - poetry config pypi-token.pypi $PYPI_API_TOKEN
    - poetry publish
