stages:
  - tests
  - e2e
  - release

.poetry_install: &poetry_install
  - python -m pip install --user pipx
  - python -m pipx ensurepath
  - source ~/.profile
  - pipx install poetry~=2.1.1
  - poetry install --no-interaction --no-root --extras "test dev"

.install_pydev_for_3_13_only: &install_pydev_for_3_13_only
  - |- 
        if  [[ $(python --version) == 'Python 3.13'* ]]; then
            apt update; 
            apt install -y libopenblas-dev gfortran; 
        fi

test:
  image: python:$VERSION
  needs: []
  stage: tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - *install_pydev_for_3_13_only
    - *poetry_install
    - poetry run black tergite --check
    - poetry run pytest tests/
  parallel:
    matrix:
      - VERSION: ['3.9-slim', '3.10-slim', '3.11-slim', '3.12-slim', '3.13-bookworm']

e2e:
  needs: []
  image: docker:latest
  services:
    - name: docker:dind
  stage: e2e
  when: manual
  manual_confirmation: 'Are you sure you want to run the end-to-end test?'
  variables:
    FRONTEND_REPO: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/tergite-frontend.git"
    BACKEND_REPO: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/tergite-backend.git"
    BACKEND_BRANCH: "main"
    FRONTEND_BRANCH: "main"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v.*$/
  before_script:
    - docker info
    - apk update && apk add --no-cache curl bash build-base cmake
      openssl-dev zlib-dev libffi-dev make git gfortran openblas-dev gnupg
      tar xz bluez-dev bzip2-dev dpkg-dev dpkg findutils gcc gdbm-dev libc-dev libnsl-dev hdf5-dev
      libtirpc-dev linux-headers ncurses-dev openssl-dev pax-utils readline-dev sqlite-dev tcl-dev
      tk tk-dev util-linux-dev xz-dev
    - curl -fsSL https://pyenv.run | bash
    - export PYENV_ROOT="$HOME/.pyenv"
    - if [ -d $PYENV_ROOT/bin ]; then export PATH="$PYENV_ROOT/bin:$PATH"; fi
    - eval "$(pyenv init - sh)"
    - pyenv install ${PYTHON_VERSION}
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  script:
    - . "$HOME/.cargo/env"
    - pyenv local ${PYTHON_VERSION}
    - ./e2e_test.sh
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.9', '3.10', '3.11', '3.12', '3.13']

deploy staging:
  stage: release
  needs:
    - test
    - e2e
  environment: staging
  image: python:3.9-slim
  rules:
    - if: $SHOULD_PUBLISH_TO_STAGING == "true" && $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - *poetry_install
    - poetry config repositories.test-pypi https://test.pypi.org/legacy/
    - poetry config pypi-token.test-pypi $TEST_PYPI_API_TOKEN
    - poetry publish -r test-pypi

deploy production:
  stage: release
  needs:
    - test
    - e2e
  environment: production
  image: python:3.9-slim
  rules:
    - if: $SHOULD_PUBLISH_TO_PROD == "true" && $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - *poetry_install
    - poetry config pypi-token.pypi $PYPI_API_TOKEN
    - poetry publish
