image: python:3.8

definitions:
  caches:
    poetry:
      key:
        files:
          - "poetry.lock"
      path: "$HOME/.cache/pypoetry/virtualenvs"
  steps:
    - step: &Test-step
        name: test
        caches:
            - pip
            - poetry
        script:
          - pip install -U pip
          - pip install --user pipx
          - export PATH="$HOME/.local/bin:$PATH"
          - pipx ensurepath
          - pipx install poetry
          - poetry install
          - source $(poetry env info --path)/bin/activate
          - pytest tests
          - deactivate
    - step: &Lint-step
        name: lint
        caches:
            - pip
            - poetry
        script:
          - if [ "${SHOULD_LINT}" != "true" ]; then printf "linting not enabled"; exit; fi
          - pip install -U pip
          - pip install --user pipx
          - export PATH="$HOME/.local/bin:$PATH"
          - pipx ensurepath
          - pipx install poetry
          - poetry install
          - source $(poetry env info --path)/bin/activate
          - black tergite_qiskit_connector --check
          - deactivate

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *Lint-step
        - step: *Test-step

  tags:
    "v*":
      - parallel:
        - step: *Lint-step
        - step: *Test-step
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git pull -r $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG does not exist"
            - git push $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG already exists"

  branches:
    main:
      - parallel:
          - step: *Lint-step
          - step: *Test-step
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git pull -r $DOWNSTREAM_REPO main || echo "main branch does not exist"
            - git push $DOWNSTREAM_REPO main