[tool.poetry]
name = "tergite-qiskit-connector"
version = "0.0.1"
description = "qiskit provider for the Tergite quantum computers"
authors = ["Miroslav Dobsicek <dobsicek@chalmers.se>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "tergite_qiskit_connector"}]

[tool.poetry.dependencies]
python = "^3.8"
requests = ">=2.25.1"
python-dateutil = ">=2.8.1"
python-multipart = ">=0.0.5"
qiskit-terra = "0.22.0"
pandas = ">=1.4.2"
tqdm = ">=4.64.1"
qiskit-aer = ">=0.11.0"
qiskit-experiments = ">=0.4.0"
qiskit-ibmq-provider = ">=0.19.2"
qiskit-ignis = ">=0.7.1"
more-itertools = ">=8.14.0"
matplotlib = ">=3.5.3"
matplotlib-inline = ">=0.1.6"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
